FROM node:11.15.0-slim as builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm install react-scripts@3.0.0 -g --silent
COPY . /usr/src/app
RUN npm run build

# Production
FROM nginx:1.15-alpine

# For react-router
RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

# Copy built dependencies across
COPY --from=builder /usr/src/app/build /usr/share/nginx/html

EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]

